config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy, :index]
  resources :grocery_stores, except: [:destroy, :edit, :update, :create, :new]
  resources :visits
  resources :items, except: [:destroy, :edit, :update, :create, :new]
  get '/login' => 'sessions#new', as: "login"
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy', as: "logout"
  get '/signup' => 'users#new', as: 'signup'
  root 'application#home'
  get '/interesting_facts'=> 'application#interesting_facts'
  get '/users/:id/covid' => 'users#covid', as: 'covid'
  patch '/users/:id/covid_notify' => 'users#covid_notify'
  get '/about'=> 'application#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/grocery_store.rb
require 'geocoder'
class GroceryStore < ApplicationRecord
    geocoded_by :address
    after_validation :geocode
    has_many :visits
    has_many :users, through: :visits
    has_many :missing_items
    has_many :items, through: :missing_items
    validates_with AddressValidator

    def self.list_by_distance(user)
        self.all.sort_by{|store| store.distance_to(user) }
    end
    def chain_name
        "#{self.chain}- #{self.address}"
    end

    def self.most_visits
        self.all.sort_by{|store| -store.visits.count }.slice(0, 3)
    end 
    def self.least_visits
        self.all.sort_by{|store| store.visits.count }.slice(0, 3)
    end 

    def ordered_visits
        self.visits.sort_by{|visit| visit.date}.reverse
      end
end

app/models/visit.rb
class Visit < ApplicationRecord
    belongs_to :user
    belongs_to :grocery_store
    accepts_nested_attributes_for :grocery_store
    validate :date_cannot_be_in_the_future
    validates :notes, length: { maximum: 500 }
    validates :user, :uniqueness => {:scope => [:date, :grocery_store], 
    message: ->(object, data) do
        "#{object.user.name}, the visit to this store on this date has already been saved."
      end}
      
      def date_formated
        self.date.strftime("%d of %B, %Y") 
      end

      def date_cannot_be_in_the_future
        errors.add(:date, "can't be in the future") if !date.blank? and date > Date.today
      end

      def self.sick_users(sick_visit)
        relevant_visits= self.all.select {|visit| visit.user==sick_visit.user && visit.date>=sick_visit.date}
        visit_array=[]
        relevant_visits.each do |vis|
          visit_array+= self.all.select{|visit| visit.grocery_store==vis.grocery_store && visit.date==vis.date}
        end
        users=visit_array.map{|visit| visit.user}.uniq
        users.each do |user| 
          user.update_column(:notify, true)
          user.update_column(:sick_date, sick_visit.date)
        end
        users.count
      end
      
      def self.busy_day
        day=self.group_by_day_of_week(:date).count.max_by{ |k, v| v }[0]
        case day
        when 0
          "Sunday"
        when 1
          "Monday"
        when 2
          "Tuesday"
        when 3
          "Wednesday"
        when 4
          "Thursday"
        when 5
          "Friday"
        when 6
          "Saturday"
        end
      end

      def self.not_busy_day
        day=self.group_by_day_of_week(:date).count.min_by{ |k, v| v }[0]
        case day
        when 0
          "Sunday"
        when 1
          "Monday"
        when 2
          "Tuesday"
        when 3
          "Wednesday"
        when 4
          "Thursday"
        when 5
          "Friday"
        when 6
          "Saturday"
        end
      end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
    before_action :redirect_user
    before_action :set_visit, only: [:show, :edit, :update, :destroy]
    
    def new
        @visit = current_user.visits.build
        if params[:admin] == "true"
            @user.update_column(:notify, false)
            render 'visits/admin_new'
        end
    end
    
    def create
        if params[:visit][:grocery_store_id]
            @visit = Visit.new(visit_params)
        else
            @visit = Visit.new(admin_visit_params)
        end
        @visit.user_id = current_user.id if current_user
        if @visit.save
            assign_missing_items
        redirect_to visit_path(@visit)
        else
            flash[:error_messages]=@visit.errors.full_messages
        render :new
        end
    end

    def edit
        redirect_to "/" unless current_user == @visit.user
    end
    def update
        if @visit.update(visit_params)
            redirect_to visit_path(@visit)
          else
            flash[:error_messages]=@visit.errors.full_messages
            render :edit
          end
    end
    def destroy
        @visit.destroy
        redirect_to user_path(current_user)
    end
    
    private

    def set_visit
        @visit = Visit.find(params[:id])
    end

    def visit_params
        params.require(:visit).permit(:grocery_store_id, :notes, :user_id, :date, grocery_store: [:item_ids])
    end

    def admin_visit_params
        params.require(:visit).permit(:notes, :user_id, :date, grocery_store: [:item_ids], grocery_store_attributes: [:chain, :address])
    end

    def assign_missing_items
        if params[:visit][:grocery_store_id]
            store=GroceryStore.find(params[:visit][:grocery_store_id].to_i)
        else 
            store=GroceryStore.all.last
        end 
        ids=params[:grocery_store][:item_ids].map{ |id| id.to_i }
        ids.each do |id| 
            MissingItem.create(grocery_store_id: store.id, item_id: id, date: @visit.date) if id>0
        end
    end

end

app/views/visits/_form.html.erb
<%= form_for @visit do |f| %><br/>
<%= f.label "User:" %> <%=@visit.user.name%><br/>
<%= f.label "Select Grocery Store From List:" %>
<%= f.collection_select :grocery_store_id, GroceryStore.list_by_distance(current_user), :id, :chain_name  %><br/>
<%= f.label "Date of Visit:" %> 
<%= f.date_select(:date, :order => [:month, :day, :year]) %><br/>
<%= f.label "Select Missing Items:" %> <br/>
<%= fields_for :grocery_store, @visit.grocery_store do |f| %>
  <%= f.collection_check_boxes :item_ids, Item.all, :id, :name do |b| %>
        <%= b.label class:"label-checkbox" do%>
         <%=b.check_box + b.text%>
        <%end%>
    <% end %>
  <% end %>
  <br/>
  <%= f.label "Notes:" %><br/>
  <%= f.text_area :notes %><br/>
  <%= f.submit %><br/>
  <% end %>

  <%if flash[:error_messages]%>
<%flash[:error_messages].each do |error| %><br/>
<%=error%>
<%end%>
<%end%>

app/views/visits/admin_new.html.erb
<h1> Create Visit With New Grocery Store </h1>
<div class="forms">
<%= form_for @visit do |f| %><br/>
<%= f.label "User:" %> <%=@visit.user.name%><br/>

<%if current_user.id==1%>
<%= f.label "Make a New Grocery Store (Admin Only):" %><br/>
 <%= f.fields_for :grocery_store, @visit.build_grocery_store do |grocery_stores_fields| %>
    <%= f.label "Grocery Store Chain:" %>
    <%= grocery_stores_fields.text_field :chain %>
    <%= f.label "Grocery Store Address:" %>
    <%= grocery_stores_fields.text_field :address %><br/>
  <% end %>
<%end%>

<%= f.label "Date of Visit:" %> 
<%= f.date_select(:date, :order => [:month, :day, :year]) %><br/>
<%= f.label "Select Missing Items:" %> <br/>
<%= fields_for :grocery_store, @visit.grocery_store do |f| %>
  <%= f.collection_check_boxes :item_ids, Item.all, :id, :name do |b| %>
        <%= b.label class:"label-checkbox" do%>
         <%=b.check_box + b.text%>
        <%end%>
    <% end %>
  <% end %>
  <br/>
  <%= f.label "Notes:" %><br/>
  <%= f.text_area :notes %><br/>
  <%= f.submit %><br/>
  <% end %>
</div>
  <%if flash[:error_messages]%>
<%flash[:error_messages].each do |error| %><br/>
<%=error%>
<%end%>
<%end%>
<img class= "account_image" src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/a010-markusspiske-jan19-msp_1901_4189.jpg?auto=format&bg=transparent&con=3&cs=srgb&dpr=1&fm=jpg&ixlib=php-3.1.0&mark=rawpixel-watermark.png&markalpha=90&markpad=13&markscale=10&markx=25&q=75&usm=15&vib=3&w=1400&s=923c6aeea6cfcf42101c767900503cc4">

app/views/visits/edit.html.erb
<h1> Edit Visit </h1>
<div class="forms">
   <%= render 'form' %>
   </div>
<img class= "account_image" src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/a010-markusspiske-jan19-msp_1901_4189.jpg?auto=format&bg=transparent&con=3&cs=srgb&dpr=1&fm=jpg&ixlib=php-3.1.0&mark=rawpixel-watermark.png&markalpha=90&markpad=13&markscale=10&markx=25&q=75&usm=15&vib=3&w=1400&s=923c6aeea6cfcf42101c767900503cc4">

app/views/visits/new.html.erb
<h1> Create New Visit </h1>
<div class="forms">
<%= render 'form' %>
</div>
<img class= "account_image" src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/a010-markusspiske-jan19-msp_1901_4189.jpg?auto=format&bg=transparent&con=3&cs=srgb&dpr=1&fm=jpg&ixlib=php-3.1.0&mark=rawpixel-watermark.png&markalpha=90&markpad=13&markscale=10&markx=25&q=75&usm=15&vib=3&w=1400&s=923c6aeea6cfcf42101c767900503cc4">

app/views/visits/show.html.erb
<h1>Grocery Store Visit on <%=@visit.date.strftime("%d of %B, %Y")%> </h1>
<h3> Store: <%=@visit.grocery_store.chain%> <%=link_to @visit.grocery_store.address, grocery_store_path(@visit.grocery_store) %> </h3>
<h3> User: <%=@visit.user.name%> </h3>
<h3> Date: <%=@visit.date.strftime("%d of %B, %Y")%> </h3>
<h3> Notes: </h3>
<p><%=@visit.notes%></p>
<%if current_user == @visit.user %>
<%= button_to "Edit", edit_visit_path, method: :get%>
<%= button_to "Delete", @visit, method: "delete", data: {confirm: "Are you sure you want to delete this visit"}%>
<%end %>
<img class= "account_image" src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/a010-markusspiske-jan19-msp_1901_4189.jpg?auto=format&bg=transparent&con=3&cs=srgb&dpr=1&fm=jpg&ixlib=php-3.1.0&mark=rawpixel-watermark.png&markalpha=90&markpad=13&markscale=10&markx=25&q=75&usm=15&vib=3&w=1400&s=923c6aeea6cfcf42101c767900503cc4">
<div>