config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy, :index]
  resources :grocery_stores, except: [:destroy, :edit, :update, :create, :new]
  resources :visits
  resources :items, except: [:destroy, :edit, :update, :create, :new]
  get '/login' => 'sessions#new', as: "login"
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy', as: "logout"
  get '/signup' => 'users#new', as: 'signup'
  root 'application#home'
  get '/interesting_facts'=> 'application#interesting_facts'
  get '/users/:id/covid' => 'users#covid', as: 'covid'
  patch '/users/:id/covid_notify' => 'users#covid_notify'
  get '/about'=> 'application#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Validations
    geocoded_by :address
    after_validation :geocode
    has_many :visits
    has_many :grocery_stores, through: :visits
    has_secure_password

    validates :name, presence: true
    validates :name, uniqueness: true
    validates :address, presence: true
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
    validates :password, length: { in: 6..20 }
   
    validates_with AddressValidator

    def ordered_visits
      self.visits.sort_by{|visit| visit.date}.reverse
    end

    def visits_dates
      self.visits.uniq(&:date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update]

  def show
    redirect_user
    redirect_to "/" unless current_user.id == params[:id].to_i
    if params[:click] == "true"
      @user.update_column(:notify, false)
      @user.update_column(:sick_date, nil)
      redirect_to @user
    end
  end
  def edit 
    redirect_user
    redirect_to "/" unless current_user.id == params[:id].to_i
  end
  def new
    @user = User.new
  end
    
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to user_path(@user)
    else
      flash[:error_messages]=@user.errors.full_messages
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:error_messages]=@user.errors.full_messages
      render :edit
    end
  end

  def destroy
    set_user.destroy
    redirect_to '/login'
  end

  def covid
    redirect_user
    set_user
  end

  def covid_notify
    @visit=Visit.find(params[:user][:visit_ids])
    @count=Visit.sick_users(@visit)
    render 'users/covid_notify'
  end
    
  private
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:name, :address, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div>
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/>
  <%= f.label :password %>
  <%= f.password_field :password %><br/>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br/>
  <%= f.label :address %>
  <%= f.text_field :address %><br/>
  <%= f.label :email %>
  <%= f.text_field :email %><br/>

  <%= f.submit %>
<% end %>
</div>

<div class= "error">
<%if flash[:error_messages]%>
<%flash[:error_messages].each do |error| %><br/>
<%=error%>
<%end%>
<%end%>
</div>

app/views/users/covid.html.erb
<h1> The visit date you got sick: </h1>

<div class="covid_form">
<%= form_for @user, as: :user, url: "/users/#{@user.id}/covid_notify", method: :patch do |f| %><br/>
<%= f.collection_select :visit_ids, @user.visits_dates, :id, :date_formated  %><br/><br/>
  <%= f.submit "Notify Others" %><br/>
<% end %>
</div>

<img class= "account_image" src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/a010-markusspiske-jan19-msp_1901_4189.jpg?auto=format&bg=transparent&con=3&cs=srgb&dpr=1&fm=jpg&ixlib=php-3.1.0&mark=rawpixel-watermark.png&markalpha=90&markpad=13&markscale=10&markx=25&q=75&usm=15&vib=3&w=1400&s=923c6aeea6cfcf42101c767900503cc4">

app/views/users/covid_notify.html.erb
<h2><%if @count<2 %>
<%= "You did not potentially infect anyone in this website" %> <br/>
<%else %>
<%= "We have notified #{pluralize(@count-1, "person")} that may have been infected."%> <br/>
<%end%> <br/>
Please do not visit the grocery stores while sick! <br/>
Thank you!</h2>
<img class= "stay_home" class="w3-hover-opacity" src="https://cdn.pixabay.com/photo/2020/04/12/16/55/stay-home-5034982_960_720.jpg" alt="Stay Home, Corona, Virus, Pandemic, Covid-19, Curfew">
<img class= "account_image" src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/a010-markusspiske-jan19-msp_1901_4189.jpg?auto=format&bg=transparent&con=3&cs=srgb&dpr=1&fm=jpg&ixlib=php-3.1.0&mark=rawpixel-watermark.png&markalpha=90&markpad=13&markscale=10&markx=25&q=75&usm=15&vib=3&w=1400&s=923c6aeea6cfcf42101c767900503cc4">

app/views/users/edit.html.erb
<h1> Edit Your Account Information </h1>
   <%= render 'form' %>

<img class= "account_image" src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/a010-markusspiske-jan19-msp_1901_4189.jpg?auto=format&bg=transparent&con=3&cs=srgb&dpr=1&fm=jpg&ixlib=php-3.1.0&mark=rawpixel-watermark.png&markalpha=90&markpad=13&markscale=10&markx=25&q=75&usm=15&vib=3&w=1400&s=923c6aeea6cfcf42101c767900503cc4">

app/views/users/new.html.erb
<h1> Create a New User </h1>
<div class="forms">
   <%= render 'form' %>
</div>
<img class= "account_image" src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/a010-markusspiske-jan19-msp_1901_4189.jpg?auto=format&bg=transparent&con=3&cs=srgb&dpr=1&fm=jpg&ixlib=php-3.1.0&mark=rawpixel-watermark.png&markalpha=90&markpad=13&markscale=10&markx=25&q=75&usm=15&vib=3&w=1400&s=923c6aeea6cfcf42101c767900503cc4">

app/views/users/show.html.erb
<%if @user.notify%>
<div id="notification">
<h5> NOTIFICATION: On <%=@user.sick_date.strftime("%d of %B, %Y")%> you may have shared a grocery store visit with someone with COVID! </h5>
<%= button_to "Dismiss", user_path(@user), method: :get, params: {click: :true} %>
<%end%>
</div>

<h1>Hi There, <%= @user.name %>!</h1>

<%if current_user.admin %>
<h2 style="font-style: italic;"> This is an Admin Account </h2>
<%end%>

<h3> Contact Information: </h3>
<p>Your Address: <%= @user.address %><br/>Your Email: <%= @user.email%></p>

<h2> Recent Visits: </h2>
<ol>
<% @user.ordered_visits.each do |visit| %>
<li>Grocery Store Visit on <%=link_to visit.date.strftime("%d of %B, %Y"), visit_path(visit)%> </li>
<%end %>
</ol>

<div class= "buttons">

<%=button_to "Submit New Visit", '/visits/new', method: "get"%>
<%if current_user.admin %>
<%=button_to "Submit New Visit with New Grocery Store", '/visits/new', method: "get", params: {admin: :true}%>
<%end%>
<%=button_to "Edit your Account", "/users/#{@user.id}/edit", method: "get"%>
<%=button_to "Logout", logout_path, method: 'post'%>
</div>

<img class= "account_image" src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/a010-markusspiske-jan19-msp_1901_4189.jpg?auto=format&bg=transparent&con=3&cs=srgb&dpr=1&fm=jpg&ixlib=php-3.1.0&mark=rawpixel-watermark.png&markalpha=90&markpad=13&markscale=10&markx=25&q=75&usm=15&vib=3&w=1400&s=923c6aeea6cfcf42101c767900503cc4">