config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy, :index]
  resources :grocery_stores, except: [:destroy, :edit, :update, :create, :new]
  resources :visits
  resources :items, except: [:destroy, :edit, :update, :create, :new]
  get '/login' => 'sessions#new', as: "login"
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy', as: "logout"
  get '/signup' => 'users#new', as: 'signup'
  root 'application#home'
  get '/interesting_facts'=> 'application#interesting_facts'
  get '/users/:id/covid' => 'users#covid', as: 'covid'
  patch '/users/:id/covid_notify' => 'users#covid_notify'
  get '/about'=> 'application#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :missing_items
    has_many :grocery_stores, through: :missing_items

    def self.search(query)
        if query.present?
          where('NAME like ?', "%#{query}%")
        else
          self.all
        end
      end
      def self.most_missing
        self.all.sort_by{|item| -item.missing_items.count}.first
      end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
            @items = Item.search(params[:query])
    render 'index'
    end
    def show
        @item=Item.find(params[:id])
        if current_user
        @stores=GroceryStore.list_by_distance(current_user).select{|store| !store.items.include?(@item)}
        else 
            @stores=GroceryStore.all.select{|store| !store.items.include?(@item)}
        end
    end
end

app/views/items/index.html.erb
<h1> List of Items </h1>

<div class="search">
<%= form_tag items_path, method: :get do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>
</div>

<div class="row">
<% @items.each do |item| %>
<div class="card" style="width: 12rem;">
  <div class="card-body">
    <h5 class="card-title"><%=link_to item.name, item_path(item)%></h5>
     <h6><%=item.category%><br/></h6>
  </div>
</div>
<%end%>
</div>

app/views/items/show.html.erb
<h1> <%=@item.name%> </h1> 
<h2> Category: <%=@item.category%></h2>
<h2> Avaliable at:</h2>
<div class="row">
<% @stores.each do |store| %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%=store.chain%></h5>
    <%if current_user %>
    <p class="card-text"><%="#{store.distance_to(current_user).round(2)} miles away from you"%></p>
       <%end%>
     </h3><%=link_to store.address, grocery_store_path(store)%><br/></h3>
  </div>
</div>
<%end%>
</div>