config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy, :index]
  resources :grocery_stores, except: [:destroy, :edit, :update, :create, :new]
  resources :visits
  resources :items, except: [:destroy, :edit, :update, :create, :new]
  get '/login' => 'sessions#new', as: "login"
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy', as: "logout"
  get '/signup' => 'users#new', as: 'signup'
  root 'application#home'
  get '/interesting_facts'=> 'application#interesting_facts'
  get '/users/:id/covid' => 'users#covid', as: 'covid'
  patch '/users/:id/covid_notify' => 'users#covid_notify'
  get '/about'=> 'application#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/grocery_store.rb
require 'geocoder'
class GroceryStore < ApplicationRecord
    geocoded_by :address
    after_validation :geocode
    has_many :visits
    has_many :users, through: :visits
    has_many :missing_items
    has_many :items, through: :missing_items
    validates_with AddressValidator

    def self.list_by_distance(user)
        self.all.sort_by{|store| store.distance_to(user) }
    end
    def chain_name
        "#{self.chain}- #{self.address}"
    end

    def self.most_visits
        self.all.sort_by{|store| -store.visits.count }.slice(0, 3)
    end 
    def self.least_visits
        self.all.sort_by{|store| store.visits.count }.slice(0, 3)
    end 

    def ordered_visits
        self.visits.sort_by{|visit| visit.date}.reverse
      end
end

app/controllers/grocery_stores_controller.rb
class GroceryStoresController < ApplicationController
    def index
        delete_old_missing_items
        if current_user
            @grocerystores=GroceryStore.list_by_distance(current_user)
        else 
            @grocerystores=GroceryStore.all
        end
    end
    def show
        delete_old_missing_items
        @store=GroceryStore.find(params[:id])
        @user= current_user
        @items=@store.items.uniq
    end
    def delete_old_missing_items
        MissingItem.where('date < ?', 7.days.ago).destroy_all
    end
end

app/helpers/grocery_stores_helper.rb
module GroceryStoresHelper
end

app/views/grocery_stores/index.html.erb
<style>
h1 {
    padding: 20px;
}
.row {
    padding-left: 60px;
}
</style>
<h1> List of Grocery Stores </h1>
<div class="row">
<% @grocerystores.each do |store| %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%=store.chain%></h5>
    <%if current_user %>
    <p class="card-text"><%="#{store.distance_to(current_user).round(2)} miles away from you"%></p>
       <%end%>
     </h3><%=link_to store.address, grocery_store_path(store)%><br/></h3>
  </div>
</div>
<%end%>
</div>

app/views/grocery_stores/show.html.erb
<h1 style="display:inline;"><%= @store.chain %></h1> <h3 style="display:inline;"><%= @store.address%></h3>
<br/>
<h3> Missing Items: </h3>
<ul> <%@items.each do |item| %>
<li><%=item.name%> </li>
<%end%>
</ul>

<h2> Recent Visits: </h2>
<ol>
<% @store.ordered_visits.each do |visit| %>
<li><%= link_to visit.date.strftime("%d of %B, %Y"), visit_path(visit)%> By: <%= visit.user.name%></li>
<ul><li>Notes: <%= visit.notes%> </li></ul>
<%end%>
</ol>

<h4><%=link_to "Go back to all grocery stores", grocery_stores_path %></h4>
<img class= "account_image" src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/a010-markusspiske-jan19-msp_1901_4189.jpg?auto=format&bg=transparent&con=3&cs=srgb&dpr=1&fm=jpg&ixlib=php-3.1.0&mark=rawpixel-watermark.png&markalpha=90&markpad=13&markscale=10&markx=25&q=75&usm=15&vib=3&w=1400&s=923c6aeea6cfcf42101c767900503cc4">